---
- name: Load kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    persistent: present
    state: present
  with_items:
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack
    - ip_tables
    - ip_set
    - xt_set
    - ipt_set
    - ipt_rpfilter
    - ipt_REJECT
    - ipip
    - br_netfilter


- name: Modify kernel parameters
  block:
    - name: Adding a kernel parameter configuration file
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        line: "{{ item }}"
        insertafter: EOF
      with_items:
        - "# kubernetes "
        - "net.ipv4.ip_forward = 1"
        - net.bridge.bridge-nf-call-iptables = 1
        - "# kernel version >= 5.4.256 Remove. 3.10 need open set value 1"
        - "#fs.may_detach_mounts = 1"
        - vm.overcommit_memory=1
        - vm.panic_on_oom=0
        - fs.inotify.max_user_watches=89100
        - fs.file-max=52706963
        - fs.nr_open=52706963
        - net.netfilter.nf_conntrack_max=2310720
        - net.ipv4.tcp_keepalive_time = 600
        - net.ipv4.tcp_keepalive_probes = 3
        - net.ipv4.tcp_keepalive_intvl =15
        - net.ipv4.tcp_max_tw_buckets = 36000
        - net.ipv4.tcp_tw_reuse = 1
        - net.ipv4.tcp_max_orphans = 327680
        - net.ipv4.tcp_orphan_retries = 3
        - net.ipv4.tcp_syncookies = 1
        - net.ipv4.tcp_max_syn_backlog = 16384
        - net.ipv4.tcp_timestamps = 0
        - net.core.somaxconn = 16384
        - net.ipv6.conf.all.disable_ipv6 = 0
        - net.ipv6.conf.default.disable_ipv6 = 0
        - net.ipv6.conf.lo.disable_ipv6 = 0
        - net.ipv6.conf.all.forwarding = 1
        - "# kubernetes EOF"
    - name: sysctl -p 
      ansible.builtin.shell: >
        sysctl -p