---
- name: Download helm packages
  ansible.builtin.get_url:
    url: https://get.helm.sh/helm-v3.12.3-linux-amd64.tar.gz
    dest: "{{ deploy_dir }}/packages/"
    checksum: sha256:1b2313cd198d45eab00cc37c38f6b1ca0a948ba279c29e322bdf426d406129b5
    mode: 0755
  delegate_to: 127.0.0.1
  run_once: yes
  tags:
    - download-helm
    - install-helm

- name: Install helm
  block:
    - name: Unzip the hlem installer
      ansible.builtin.shell: >
        tar zxvf {{ deploy_dir }}/packages/helm-v3.12.3-linux-amd64.tar.gz -C /tmp
    - name: Move helm to /usr/local/bin/
      ansible.builtin.shell: >
        mv /tmp/linux-amd64/helm /usr/local/bin/
  delegate_to: 127.0.0.1
  run_once: yes
  tags:
    - install-helm

