---
- name: Install cilium
  block:
    - name: Add helm repo
      ansible.builtin.shell: >
        helm repo add cilium https://helm.cilium.io
      delegate_to: 127.0.0.1
      run_once: yes
      tags:
        - helm-repo
    - name: Pull cilium chat
      ansible.builtin.shell: >
        helm pull cilium/cilium --version 1.14.2
      args:
        chdir: "{{ inventory_dir }}/{{ deploy_dir }}/packages/"
      delegate_to: 127.0.0.1
      run_once: yes
      tags:
        - pull-cilium
    - name: Unzip cilium packages
      ansible.builtin.unarchive:
        src: "{{ inventory_dir }}/{{ deploy_dir }}/packages/cilium-1.14.2.tgz"
        dest: "{{ inventory_dir }}/{{ deploy_dir }}/packages/"
        remote_src: yes
      delegate_to: 127.0.0.1
      run_once: yes
      tags:
        -  unzip-cilium
    - name: Modify the cilium image address
      ansible.builtin.replace:
        path: "{{ inventory_dir }}/{{ deploy_dir }}/packages/cilium/values.yaml"
        regexp: 'quay\.io'
        replace: 'm.daocloud.io/quay.io'
      delegate_to: 127.0.0.1
      run_once: yes
      tags:
        - update-cilium-images
    - name: helm install cilium
      ansible.builtin.shell: >
        helm install cilium cilium/cilium --namespace kube-system --set hubble.relay.enabled=true --set hubble.ui.enabled=true --set prometheus.enabled=true --set operator.prometheus.enabled=true --set hubble.enabled=true --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,http}"  --set ipam.operator.clusterPoolIPv4PodCIDRList="10.60.0.0/16" 
      args:
        chdir: "{{ inventory_dir }}/{{ deploy_dir }}/packages/cilium/"
      delegate_to: 127.0.0.1
      run_once: yes
      tags:
        - helm-install-cilium
    - name: Save values configure
      ansible.builtin.shell: >
        helm -n kube-system get values cilium >> {{ inventory_dir }}/{{ deploy_dir }}/packages/cilium/values-save.yaml
      args:
        chdir: "{{ inventory_dir }}/{{ deploy_dir }}/packages/cilium/"
      delegate_to: 127.0.0.1
      run_once: yes
      tags:
        - cilium-get-values

  tags:
    - install-cilium


