---

- name: Aliyun repository
  block:
    - name: Get aliyun CentOS-7 repository
      ansible.builtin.get_url:
        url: http://mirrors.aliyun.com/repo/Centos-7.repo
        dest: /etc/yum.repos.d/CentOS-aliyun-Base.repo

    - name: Get aliyun CentOS-7 epel repository
      get_url:
        url: http://mirrors.aliyun.com/repo/epel-7.repo
        dest: /etc/yum.repos.d/aliyun-epel-7.repo


- name: Copy kernel repository to /etc/yum.repos.d/
  block:
    - name: Copy kernel repository to /etc/yum.repos.d/
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "/etc/yum.repos.d/{{ item.dest }}"
        mode: 0644
      with_items:
        - { src: "bsc-kernel.repo", dest: "bsc-kernel.repo" }
