---
- name: Prepare some dirs
  ansible.builtin.file:
    name: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ inventory_dir }}/ssl"
    - "{{ inventory_dir }}/backup"
    - "{{ inventory_dir }}/bin/"
    - "{{ inventory_dir }}/packages/"
    - "{{ inventory_dir }}/context/"

- name: Prepare cfssl tools
  block:
    - name: Get cfssl packages
      ansible.builtin.get_url:
        url: https://github.com/cloudflare/cfssl/releases/download/v1.6.4/cfssl_1.6.4_linux_amd64
        dest: "{{ inventory_dir }}/bin/cfssl"
        checksum: sha256:https://github.com/cloudflare/cfssl/releases/download/v1.6.4/cfssl_1.6.4_checksums.txt
        mode: 0755
    - name: Get cfssljson packages
      ansible.builtin.get_url:
        url: https://github.com/cloudflare/cfssl/releases/download/v1.6.4/cfssljson_1.6.4_linux_amd64
        dest: "{{ inventory_dir }}/bin/cfssljson"
        checksum: sha256:https://github.com/cloudflare/cfssl/releases/download/v1.6.4/cfssl_1.6.4_checksums.txt
        mode: 0755

- name: Preparing CA Profiles and Signature Requests
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - {src: "ca-csr.json.j2", dest: "{{ inventory_dir }}/ssl/ca-csr.json"}
    - {src: "ca-config.json.j2", dest: "{{ inventory_dir }}/ssl/ca-config.json"}

- name: Preparing CA Profiles and Signature Requests
  ansible.builtin.shell: " cd {{ inventory_dir }}/ssl && \
      ../bin/cfssl gencert -initca ca-csr.json | ../bin/cfssljson -bare ca"