---
- name: Install CoreDNS
  block:
    - name: Add CoreDNS repo
      ansible.builtin.shell: >
        helm repo add coredns https://coredns.github.io/helm
      delegate_to: localhost
      run_once: yes
      tags:
        - helm-repo
    - name: Pull coredns chat 
      ansible.builtin.shell: >
        helm pull coredns/coredns --version 1.27.1
      args:
        chdir: "{{ inventory_dir }}/{{ deploy_dir }}/packages/"
      delegate_to: localhost
      run_once: yes
      tags:
        - pull-coredns
    - name: Unzip coredns packages
      ansible.builtin.unarchive:
        src: "{{ inventory_dir }}/{{ deploy_dir }}/packages/coredns-1.27.1.tgz"
        dest: "{{ inventory_dir }}/{{ deploy_dir }}/packages/"
        remote_src: yes
      delegate_to: localhost
      run_once: yes
      tags:
        -  unzip-coredns
    - name: Modify the coredns image address
      ansible.builtin.replace:
        path: "{{ inventory_dir }}/{{ deploy_dir }}/packages/coredns/values.yaml"
        regexp: 'coredns/coredns'
        replace: 'm.daocloud.io/docker.io/coredns/coredns'
      delegate_to: localhost
      run_once: yes
      tags:
        - update-coredns-images
    - name: Modify the coredns image address
      ansible.builtin.replace:
        path: "{{ inventory_dir }}/{{ deploy_dir }}/packages/coredns/values.yaml"
        regexp: 'registry\.k8s\.io'
        replace: 'm.daocloud.io/registry.k8s.io'
      delegate_to: localhost
      run_once: yes
      tags:
        - update-coredns-images
    - name: helm install coredns
      ansible.builtin.shell: >
        helm -n kube-system install coredns .  -f values.yaml  --set service.clusterIP={{ CLUSTER_DNS_SVC_IP }}
      args:
        chdir: "{{ inventory_dir }}/{{ deploy_dir }}/packages/coredns/"
      delegate_to: localhost
      run_once: yes
      tags:
        - helm-install-coredns
    - name: Save values configure
      ansible.builtin.shell: >
        helm -n kube-system get values coredns >> {{ inventory_dir }}/{{ deploy_dir }}/packages/coredns/values-save.yaml
      args:
        chdir: "{{ inventory_dir }}/{{ deploy_dir }}/packages/coredns/"
      delegate_to: localhost
      run_once: yes
      tags:
        - coredns-get-values
  tags:
    - install-coredns


