name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io 
        username: ${{ github.actor }} 
        password: ${{ secrets.HUB_GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/JokerDevops/kube-cluster:main
        docker push ghcr.io/JokerDevops/kube-cluster:main
